### ISSUE TITLE
Xmbc.python error

### ISSUE THREAD

**Issue by teoweehuisiang** [groggyegg/groggyegg.github.io#1]
Hello!

Im running on Leia 18.9 and i tried to install from repo but i this xmbc.python 3.0.0 could not be satisfied error. Pls advise! Thanks

**Comment by groggyegg** [comment]
I have added further instruction for Leia 18.9 in README.md. Some issue with CI changed the repository. Haven't had time to update the CI yet, will do when I have more time to fix it. Could you try again and see if it works now?

**Comment by teoweehuisiang** [comment]
It is working now! Thank you so much for the quick respond!! Appreciate it alot
