### ISSUE TITLE
Additional addon missing

### ISSUE THREAD

**Issue by LeoKodi** [groggyegg/groggyegg.github.io#5]
Hi. Thanks for this addon! 

But recently not sure why it’s not working anymore so I reinstall it. But when I reinstall, a lot of addon is not available. Google drive, script module python twitch, video YouTube, script module six, script module certifi, script module request, script module kodi six  all not available. Then it will say script module six version 0.0.0 couldn’t be satisfied. Can u pls help on this? Thx on advanced.

**Comment by groggyegg** [comment]
Are you using Kodi 18?

**Comment by LeoKodi** [comment]
Hi

Thanks for reply. Im not sure whether is it 18 but its from google play
store for my mitv so it shld be the latest version. But if im not wrong,
its 19 now right?

It is working previously but suddenly its not.

Do you have any advise on how to solve this?

THanks

**Comment by groggyegg** [comment]
Yes, latest version is 19. From the look of it, you might have upgraded from version 18 to 19 which will cause some issue. Simple solution would be to remove Kodi completely and install it again. It could also be that the Kodi from the store does not have modules included.

**Comment by groggyegg** [comment]
Closing this issue since this seems to be old. Create a new issue if it is still a problem.
