### ISSUE TITLE
Kodi 18 version 1.8.8 stopped working 5/10.

### ISSUE THREAD

**Issue by xalagaco** [groggyegg/groggyegg.github.io#6]
All links fail to play, saying check log.
Kodi 19 version 2.3.2 works fine, Dev version 2.4.0 fails as above.

**Comment by xalagaco** [comment]
Per [Reddit discussion](https://www.reddit.com/r/Addons4Kodi/comments/umab0q), downgrading resolveurl to 5.1.64 makes it work for the time being. Hoping for 1.8.9. . .

**Comment by groggyegg** [comment]
DramaCool 3.0.0 has recently been released which supports Kodi 18 and 19. Try upgrade to it and see if it works.

**Comment by xalagaco** [comment]
Fantastic! That's some great work. We appreciate your hard work. This is our go-to add-on without a viable alternative ATM, so whenever it stops working my heart drops.
